version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.31
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-243-197-120.compute-1.amazonaws.com
            # database: de94qtofg0bmo8
            database: d1kpfo6os7epqe
            
            # user: dslkdxjmaeindv
            user: akqoikyaombjcc

            # password: a563c636a0e8a7da918521b055350719744135d779f107ad6a89eae264ecffe1
            password: 2738b5e763de9605f3398b47a2103f9484b15a101167840180721b19a3fb576e
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true